
version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      -checkout
      -node/with-cache:
        key: edage
      -run:
        name: Install dependencies
        command: npm install
      -run:
        name: Run tests
        command: npm run test
